# Generated by Django 2.2.7 on 2019-11-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0003_auto_20191124_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='tenttimeout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='timeout',
            field=models.DateTimeField(null=True),
        ),
    ]
