# Generated by Django 2.2.7 on 2019-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0009_host_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='address',
        ),
        migrations.AddField(
            model_name='visit',
            name='address',
            field=models.CharField(default='innovaccer', max_length=250),
            preserve_default=False,
        ),
    ]
