# Generated by Django 2.2.7 on 2019-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0008_remove_visit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(default='inovaccer office', max_length=250),
            preserve_default=False,
        ),
    ]
