# Generated by Django 2.2.7 on 2019-11-24 19:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0002_auto_20191124_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
