# Generated by Django 2.2.7 on 2019-11-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0007_visit_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='address',
        ),
    ]
