version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgredata:/var/lib/postgresql/data/
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Entry_Management_App:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - var.env

volumes:
  postgredata:
